/* 
Author: Edward Ma
DBAS Project 2

Inserting Data to newly created table from old database
AKA The great migration.
*/
-- CONNECTED TO NW_ORIGINALDB
INSERT INTO NWNEW.CATEGORIES SELECT * FROM CATEGORIES;
INSERT INTO NWNEW.CUSTOMERS SELECT * FROM CUSTOMERS;
INSERT INTO NWNEW.EMPLOYEES SELECT * FROM EMPLOYEES; 
INSERT INTO NWNEW.SUPPLIERS SELECT * FROM SUPPLIERS;
INSERT INTO NWNEW.EMPLOYEETERRITORIES SELECT * FROM EMPLOYEETERRITORIES;
INSERT INTO NWNEW.ORDER_DETAILS SELECT * FROM ORDER_DETAILS;
INSERT INTO NWNEW.ORDERS SELECT * FROM ORDERS;
INSERT INTO NWNEW.PRODUCTS SELECT * FROM PRODUCTS;
INSERT INTO NWNEW.REGION SELECT * FROM REGION;
INSERT INTO NWNEW.SHIPPERS SELECT * FROM SHIPPERS;
INSERT INTO NWNEW.TERRITORIES SELECT * FROM TERRITORIES;


