/*  
Author: Edward Ma
Student ID: W0057568

Data Migration Project.
Enhancement #3 Part 1

Creating a new Centralized Country Table 
Using Alpha-3 Code as Primary Key
Data Source is from
https://www.iso.org/obp/ui/#search

And yes, that's All 249 of them.
*/

-- drop country table
DROP TABLE Country PURGE;

-- create country table
CREATE TABLE Country 
	(
	CountryID CHAR(3) NOT NULL,
	CountryName Varchar(50) NOT NULL,
	CONSTRAINT PK_Country PRIMARY KEY (CountryID)
	);

-- insert new value to table
INSERT INTO Country VALUES('AFG','AFGHANISTAN');
INSERT INTO Country VALUES('ALA','LAND ISLANDS');
INSERT INTO Country VALUES('ALB','ALBANIA');
INSERT INTO Country VALUES('DZA','ALGERIA');
INSERT INTO Country VALUES('ASM','AMERICAN SAMOA');
INSERT INTO Country VALUES('AND','ANDORRA');
INSERT INTO Country VALUES('AGO','ANGOLA');
INSERT INTO Country VALUES('AIA','ANGUILLA');
INSERT INTO Country VALUES('ATA','ANTARCTICA');
INSERT INTO Country VALUES('ATG','ANTIGUA AND BARBUDA');
INSERT INTO Country VALUES('ARG','ARGENTINA');
INSERT INTO Country VALUES('ARM','ARMENIA');
INSERT INTO Country VALUES('ABW','ARUBA');
INSERT INTO Country VALUES('AUS','AUSTRALIA');
INSERT INTO Country VALUES('AUT','AUSTRIA');
INSERT INTO Country VALUES('AZE','AZERBAIJAN');
INSERT INTO Country VALUES('BHS','BAHAMAS');
INSERT INTO Country VALUES('BHR','BAHRAIN');
INSERT INTO Country VALUES('BGD','BANGLADESH');
INSERT INTO Country VALUES('BRB','BARBADOS');
INSERT INTO Country VALUES('BLR','BELARUS');
INSERT INTO Country VALUES('BEL','BELGIUM');
INSERT INTO Country VALUES('BLZ','BELIZE');
INSERT INTO Country VALUES('BEN','BENIN');
INSERT INTO Country VALUES('BMU','BERMUDA');
INSERT INTO Country VALUES('BTN','BHUTAN');
INSERT INTO Country VALUES('BOL','BOLIVIA');
INSERT INTO Country VALUES('BES','BONAIRE, ST. EUSTATIUS, AND SABA');
INSERT INTO Country VALUES('BIH','BOSNIA AND HERZEGOVINA');
INSERT INTO Country VALUES('BWA','BOTSWANA');
INSERT INTO Country VALUES('BVT','BOUVET ISLAND');
INSERT INTO Country VALUES('BRA','BRAZIL');
INSERT INTO Country VALUES('IOT','BRITISH INDIAN OCEAN TERRITORY');
INSERT INTO Country VALUES('BRN','BRUNEI DARUSSALAM');
INSERT INTO Country VALUES('BGR','BULGARIA');
INSERT INTO Country VALUES('BFA','BURKINA FASO');
INSERT INTO Country VALUES('BDI','BURUNDI');
INSERT INTO Country VALUES('KHM','CAMBODIA');
INSERT INTO Country VALUES('CMR','CAMEROON');
INSERT INTO Country VALUES('CAN','CANADA');
INSERT INTO Country VALUES('CPV','CAPE VERDE');
INSERT INTO Country VALUES('CYM','CAYMAN ISLANDS');
INSERT INTO Country VALUES('CAF','CENTRAL AFRICAN REPUBLIC');
INSERT INTO Country VALUES('TCD','CHAD');
INSERT INTO Country VALUES('CHL','CHILE');
INSERT INTO Country VALUES('CHN','CHINA');
INSERT INTO Country VALUES('CXR','CHRISTMAS ISLAND');
INSERT INTO Country VALUES('CCK','COCOS (KEELING) ISLANDS');
INSERT INTO Country VALUES('COL','COLOMBIA');
INSERT INTO Country VALUES('COM','COMOROS');
INSERT INTO Country VALUES('COG','CONGO, REPUBLIC OF');
INSERT INTO Country VALUES('COD','CONGO, THE DEMOCRATIC REPUBLIC OF THE');
INSERT INTO Country VALUES('COK','COOK ISLANDS');
INSERT INTO Country VALUES('CRI','COSTA RICA');
INSERT INTO Country VALUES('CIV','C‚TE D''IVOIRE');
INSERT INTO Country VALUES('HRV','CROATIA');
INSERT INTO Country VALUES('CUB','CUBA');
INSERT INTO Country VALUES('CUW','CURAÄAO');
INSERT INTO Country VALUES('CYP','CYPRUS');
INSERT INTO Country VALUES('CZE','CZECH REPUBLIC');
INSERT INTO Country VALUES('DNK','DENMARK');
INSERT INTO Country VALUES('DJI','DJIBOUTI');
INSERT INTO Country VALUES('DMA','DOMINICA');
INSERT INTO Country VALUES('DOM','DOMINICAN REPUBLIC');
INSERT INTO Country VALUES('ECU','ECUADOR');
INSERT INTO Country VALUES('EGY','EGYPT');
INSERT INTO Country VALUES('SLV','EL SALVADOR');
INSERT INTO Country VALUES('GNQ','EQUATORIAL GUINEA');
INSERT INTO Country VALUES('ERI','ERITREA');
INSERT INTO Country VALUES('EST','ESTONIA');
INSERT INTO Country VALUES('ETH','ETHIOPIA');
INSERT INTO Country VALUES('FRO','FAEROE ISLANDS');
INSERT INTO Country VALUES('FLK','FALKLAND ISLANDS');
INSERT INTO Country VALUES('FJI','FIJI');
INSERT INTO Country VALUES('FIN','FINLAND');
INSERT INTO Country VALUES('FRA','FRANCE');
INSERT INTO Country VALUES('GUF','FRENCH GUIANA');
INSERT INTO Country VALUES('PYF','FRENCH POLYNESIA');
INSERT INTO Country VALUES('ATF','FRENCH SOUTHERN TERRITORIES');
INSERT INTO Country VALUES('GAB','GABON');
INSERT INTO Country VALUES('GMB','GAMBIA, THE');
INSERT INTO Country VALUES('GEO','GEORGIA');
INSERT INTO Country VALUES('DEU','GERMANY');
INSERT INTO Country VALUES('GHA','GHANA');
INSERT INTO Country VALUES('GIB','GIBRALTAR');
INSERT INTO Country VALUES('GBR','UK');
INSERT INTO Country VALUES('GRC','GREECE');
INSERT INTO Country VALUES('GRL','GREENLAND');
INSERT INTO Country VALUES('GRD','GRENADA');
INSERT INTO Country VALUES('GLP','GUADELOUPE');
INSERT INTO Country VALUES('GUM','GUAM');
INSERT INTO Country VALUES('GTM','GUATEMALA');
INSERT INTO Country VALUES('GGY','GUERNSEY');
INSERT INTO Country VALUES('GIN','GUINEA');
INSERT INTO Country VALUES('GNB','GUINEA-BISSAU');
INSERT INTO Country VALUES('GUY','GUYANA');
INSERT INTO Country VALUES('HTI','HAITI');
INSERT INTO Country VALUES('HMD','HEARD ISLAND AND MCDONALD ISLANDS');
INSERT INTO Country VALUES('HND','HONDURAS');
INSERT INTO Country VALUES('HKG','HONG KONG');
INSERT INTO Country VALUES('HUN','HUNGARY');
INSERT INTO Country VALUES('ISL','ICELAND');
INSERT INTO Country VALUES('IND','INDIA');
INSERT INTO Country VALUES('IDN','INDONESIA');
INSERT INTO Country VALUES('IRN','IRAN');
INSERT INTO Country VALUES('IRQ','IRAQ');
INSERT INTO Country VALUES('IRL','IRELAND');
INSERT INTO Country VALUES('IMN','ISLE OF MAN');
INSERT INTO Country VALUES('ISR','ISRAEL');
INSERT INTO Country VALUES('ITA','ITALY');
INSERT INTO Country VALUES('JAM','JAMAICA');
INSERT INTO Country VALUES('JPN','JAPAN');
INSERT INTO Country VALUES('JEY','JERSEY');
INSERT INTO Country VALUES('JOR','JORDAN');
INSERT INTO Country VALUES('KAZ','KAZAKHSTAN');
INSERT INTO Country VALUES('KEN','KENYA');
INSERT INTO Country VALUES('KIR','KIRIBATI');
INSERT INTO Country VALUES('PRK','NORTH KOREA');
INSERT INTO Country VALUES('KOR','SOUTH KOREA');
INSERT INTO Country VALUES('KWT','KUWAIT');
INSERT INTO Country VALUES('KGZ','KYRGYZSTAN');
INSERT INTO Country VALUES('LAO','LAO PEOPLES DEMOCRATIC REPUBLIC');
INSERT INTO Country VALUES('LVA','LATVIA');
INSERT INTO Country VALUES('LBN','LEBANON');
INSERT INTO Country VALUES('LSO','LESOTHO');
INSERT INTO Country VALUES('LBR','LIBERIA');
INSERT INTO Country VALUES('LBY','LIBYA');
INSERT INTO Country VALUES('LIE','LIECHTENSTEIN');
INSERT INTO Country VALUES('LTU','LITHUANIA');
INSERT INTO Country VALUES('LUX','LUXEMBOURG');
INSERT INTO Country VALUES('MAC','MACAO');
INSERT INTO Country VALUES('MKD','MACEDONIA');
INSERT INTO Country VALUES('MDG','MADAGASCAR');
INSERT INTO Country VALUES('MWI','MALAWI');
INSERT INTO Country VALUES('MYS','MALAYSIA');
INSERT INTO Country VALUES('MDV','MALDIVES');
INSERT INTO Country VALUES('MLI','MALI');
INSERT INTO Country VALUES('MLT','MALTA');
INSERT INTO Country VALUES('MHL','MARSHALL ISLANDS');
INSERT INTO Country VALUES('MTQ','MARTINIQUE');
INSERT INTO Country VALUES('MRT','MAURITANIA');
INSERT INTO Country VALUES('MUS','MAURITIUS');
INSERT INTO Country VALUES('MYT','MAYOTTE');
INSERT INTO Country VALUES('MEX','MEXICO');
INSERT INTO Country VALUES('FSM','MICRONESIA');
INSERT INTO Country VALUES('MDA','MOLDOVA');
INSERT INTO Country VALUES('MCO','MONACO');
INSERT INTO Country VALUES('MNG','MONGOLIA');
INSERT INTO Country VALUES('MNE','MONTENEGRO');
INSERT INTO Country VALUES('MSR','MONTSERRAT');
INSERT INTO Country VALUES('MAR','MOROCCO');
INSERT INTO Country VALUES('MOZ','MOZAMBIQUE');
INSERT INTO Country VALUES('MMR','MYANMAR');
INSERT INTO Country VALUES('NAM','NAMIBIA');
INSERT INTO Country VALUES('NRU','NAURU');
INSERT INTO Country VALUES('NPL','NEPAL');
INSERT INTO Country VALUES('NLD','NETHERLANDS');
INSERT INTO Country VALUES('NCL','NEW CALEDONIA');
INSERT INTO Country VALUES('NZL','NEW ZEALAND');
INSERT INTO Country VALUES('NIC','NICARAGUA');
INSERT INTO Country VALUES('NER','NIGER');
INSERT INTO Country VALUES('NGA','NIGERIA');
INSERT INTO Country VALUES('NIU','NIUE');
INSERT INTO Country VALUES('NFK','NORFOLK ISLAND');
INSERT INTO Country VALUES('MNP','NORTHERN MARIANA ISLANDS');
INSERT INTO Country VALUES('NOR','NORWAY');
INSERT INTO Country VALUES('OMN','OMAN');
INSERT INTO Country VALUES('PAK','PAKISTAN');
INSERT INTO Country VALUES('PLW','PALAU');
INSERT INTO Country VALUES('PSE','PALESTINIAN TERRITORIES');
INSERT INTO Country VALUES('PAN','PANAMA');
INSERT INTO Country VALUES('PNG','PAPUA NEW GUINEA');
INSERT INTO Country VALUES('PRY','PARAGUAY');
INSERT INTO Country VALUES('PER','PERU');
INSERT INTO Country VALUES('PHL','PHILIPPINES');
INSERT INTO Country VALUES('PCN','PITCAIRN');
INSERT INTO Country VALUES('POL','POLAND');
INSERT INTO Country VALUES('PRT','PORTUGAL');
INSERT INTO Country VALUES('PRI','PUERTO RICO');
INSERT INTO Country VALUES('QAT','QATAR');
INSERT INTO Country VALUES('REU','R?UNION');
INSERT INTO Country VALUES('ROU','ROMANIA');
INSERT INTO Country VALUES('RUS','RUSSIAN FEDERATION');
INSERT INTO Country VALUES('RWA','RWANDA');
INSERT INTO Country VALUES('BLM','SAINT BARTH?LEMY');
INSERT INTO Country VALUES('SHN','SAINT HELENA');
INSERT INTO Country VALUES('KNA','SAINT KITTS AND NEVIS');
INSERT INTO Country VALUES('LCA','SAINT LUCIA');
INSERT INTO Country VALUES('MAF','SAINT MARTIN');
INSERT INTO Country VALUES('SPM','SAINT PIERRE AND MIQUELON');
INSERT INTO Country VALUES('VCT','SAINT VINCENT AND THE GRENADINES');
INSERT INTO Country VALUES('WSM','SAMOA');
INSERT INTO Country VALUES('SMR','SAN MARINO');
INSERT INTO Country VALUES('STP','SAO TOME AND PRINCIPE');
INSERT INTO Country VALUES('SAU','SAUDI ARABIA');
INSERT INTO Country VALUES('SEN','SENEGAL');
INSERT INTO Country VALUES('SRB','SERBIA');
INSERT INTO Country VALUES('SYC','SEYCHELLES');
INSERT INTO Country VALUES('SLE','SIERRA LEONE');
INSERT INTO Country VALUES('SGP','SINGAPORE');
INSERT INTO Country VALUES('SXM','SINT MAARTEN');
INSERT INTO Country VALUES('SVK','SLOVAKIA');
INSERT INTO Country VALUES('SVN','SLOVENIA');
INSERT INTO Country VALUES('SLB','SOLOMON ISLANDS');
INSERT INTO Country VALUES('SOM','SOMALIA');
INSERT INTO Country VALUES('ZAF','SOUTH AFRICA');
INSERT INTO Country VALUES('SGS','SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS');
INSERT INTO Country VALUES('SSD','SOUTH SUDAN');
INSERT INTO Country VALUES('ESP','SPAIN');
INSERT INTO Country VALUES('LKA','SRI LANKA');
INSERT INTO Country VALUES('SDN','SUDAN');
INSERT INTO Country VALUES('SUR','SURINAME');
INSERT INTO Country VALUES('SJM','SVALBARD AND JAN MAYEN');
INSERT INTO Country VALUES('SWZ','SWAZILAND');
INSERT INTO Country VALUES('SWE','SWEDEN');
INSERT INTO Country VALUES('CHE','SWITZERLAND');
INSERT INTO Country VALUES('SYR','SYRIAN ARAB REPUBLIC');
INSERT INTO Country VALUES('TWN','TAIWAN');
INSERT INTO Country VALUES('TJK','TAJIKISTAN');
INSERT INTO Country VALUES('TZA','TANZANIA');
INSERT INTO Country VALUES('THA','THAILAND');
INSERT INTO Country VALUES('TLS','TIMOR-LESTE');
INSERT INTO Country VALUES('TGO','TOGO');
INSERT INTO Country VALUES('TKL','TOKELAU');
INSERT INTO Country VALUES('TON','TONGA');
INSERT INTO Country VALUES('TTO','TRINIDAD AND TOBAGO');
INSERT INTO Country VALUES('TUN','TUNISIA');
INSERT INTO Country VALUES('TUR','TURKEY');
INSERT INTO Country VALUES('TKM','TURKMENISTAN');
INSERT INTO Country VALUES('TCA','TURKS AND CAICOS ISLANDS');
INSERT INTO Country VALUES('TUV','TUVALU');
INSERT INTO Country VALUES('UGA','UGANDA');
INSERT INTO Country VALUES('UKR','UKRAINE');
INSERT INTO Country VALUES('ARE','UNITED ARAB EMIRATES');
INSERT INTO Country VALUES('USA','USA');
INSERT INTO Country VALUES('UMI','UNITED STATES MINOR OUTLYING ISLANDS');
INSERT INTO Country VALUES('URY','URUGUAY');
INSERT INTO Country VALUES('UZB','UZBEKISTAN');
INSERT INTO Country VALUES('VUT','VANUATU');
INSERT INTO Country VALUES('VAT','VATICAN CITY');
INSERT INTO Country VALUES('VEN','VENEZUELA');
INSERT INTO Country VALUES('VNM','VIET NAM');
INSERT INTO Country VALUES('VGB','VIRGIN ISLANDS, BRITISH');
INSERT INTO Country VALUES('VIR','VIRGIN ISLANDS, U.S.');
INSERT INTO Country VALUES('WLF','WALLIS AND FUTUNA');
INSERT INTO Country VALUES('ESH','WESTERN SAHARA');
INSERT INTO Country VALUES('YEM','YEMEN');
INSERT INTO Country VALUES('ZMB','ZAMBIA');
INSERT INTO Country VALUES('ZWE','ZIMBABWE');

-- to make sure all 249 countries are inserted.
--SELECT COUNT(CountryID) From COUNTRY WHERE COUNTRYID IS NOT NULL;